### ISSUE TITLE
小程序的setStorage方法是异步的，不应该在fail回调里return “error”

### ISSUE THREAD

**Issue by sayori-cg** [huangzijian888/TOTP-Miniapp#2]
page/index/index.js 

updateTokenStorage方法 

wx.setStorage({
            key: 'tokens',
            data: tokens,
            fail: () => {
                 return 'error';
            }
}）

应改为 =》

try {
        wx.setStorageSync('tokens', tokens)
} catch (e) {
        return "error"
}

**Comment by huangzijian888** [comment]
@kirito-cg 感谢反馈，v1.0.6 已修复
