### ISSUE TITLE
addToken方法里逻辑有误

### ISSUE THREAD

**Issue by sayori-cg** [huangzijian888/TOTP-Miniapp#3]
pages/index/index.js

addToken方法里调用了updateTokenStorage方法

let result = this.updateTokenStorage(tokens);
        if (!result) {
          wx.showModal({
              title: '错误',
              content: '更新数据发生异常',
              showCancel: false,
         })
}

updateTokenStorage是一定会返回success或error字符串的，所以这个if代码块的判断条件可改为 result === 'error'

**Comment by huangzijian888** [comment]
感谢反馈，已修复！
